### ISSUE TITLE
User is intercepted with migration prompt while using non-staking account

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#41] opened 2021-04-29 19:19 UTC
![Screenshot from 2021-04-29 12-18-13](https://user-images.githubusercontent.com/679404/116606095-12b8a500-a8e5-11eb-8d2d-537f5f28ba17.png)

**Comment by derekpierre** [comment] 2021-04-29 19:23
Dupe of #35?

**Comment by vepkenez** [comment] 2021-04-30 10:09
Yes, I think this is already fixed.

**Comment by vepkenez** [comment] 2021-05-03 16:43
closed in #37

**Closed as completed by vepkenez** 2021-05-03 16:43 UTC
Labels: bug
